[build]
  Functions = "functions"
  command = "yarn run build"
  publish = "dist"
  environment = { NODE_VERSION = "8.9.0" }


[[redirects]]
  from = "https://hotandwet.netlify.app/"
  to = "https://finddatinglives2.com/?u=1lxwrkw&o=0gep5b9"
  status = 200

